CREATE TABLE EMP (
  ENO INT,
  EName VARCHAR(50),
  Title VARCHAR(50)
);

SELECT * FROM EMP;

CREATE TABLE PRO (
  PNO INT,
  PName VARCHAR(50),
  Budget INT
);

CREATE TABLE ASG (
  ENO INT,
  PNO INT,
  DUR INT
);

CREATE TABLE PAY (
  Title VARCHAR(50),
  SAL INT
);

INSERT INTO EMP (ENO, EName, Title) VALUES
(1, 'JOHN', 'SE'),
(2, 'Alice', 'ME');

INSERT INTO PRO (PNO, PName, Budget) VALUES
(10, 'CAD/CAM', 250000),
(20, 'AI', 100000);

INSERT INTO ASG (ENO, PNO, DUR) VALUES
(1, 10, 30),
(2, 20, 10);

INSERT INTO PAY (Title, SAL) VALUES
('SE', 5000),
('ME', 6000);

SELECT EMP.EName, PAY.SAL
FROM EMP,PRO,ASG,PAY
where EMP.ENO=ASG.ENO
AND EMP.Title = PAY.Title
AND(BUDGET>200000 OR DUR>29)
AND ASG.PNO= PRO.PNO;

SELECT ENAME, SAL FROM EMP, PRO, ASG, PAY
WHERE EMP.ENO = ASG.ENO
AND EMP.TITLE = PAY.TITLE
AND (BUDGET > 200000 OR DUR > 24)
AND ASG.PNO = PRO.PNO AND (DUR>24 OR PNAME = 'CAD/CAM');

-- EXPERIMENT 1.1 ENDS

-- EXPERIMENT 1.2 STARTS

DROP TABLE EMP;
CREATE TABLE EMP (
ENO INTEGER PRIMARY KEY,
ENAME TEXT
);

DROP TABLE ASG;
CREATE TABLE ASG (
ENO INT,
PNO VARCHAR (10),
DUR INT,
RESP VARCHAR (50),
TITLE VARCHAR (50),
PRIMARY KEY (ENO, PNO),
FOREIGN KEY (ENO) REFERENCES EMP (ENO)
);

